// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "孩子给我的启示";

const lessonData = [
    // ===== 第1段（小标题：你的筷子好温暖啊） =====
    ["你的", "nǐ de", "your", "awak punya"],
    ["筷子", "kuài zi", "chopsticks", "penyepit"],
    ["好", "hǎo", "very", "sangat"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["啊", "a", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["一个", "yī gè", "a", "sebuah"],
    ["寒冷", "hán lěng", "cold", "sejuk"],
    ["落雨", "luò yǔ", "rainy", "hujan"],
    ["的", "de", "", ""],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["回家", "huí jiā", "return home", "pulang ke rumah"],
    ["很晚", "hěn wǎn", "very late", "lewat"],
    ["，", "", "", ""],
    ["独自", "dú zì", "alone", "bersendirian"],
    ["一个人", "yī gè rén", "alone", "seorang diri"],
    ["吃", "chī", "eat", "makan"],
    ["“", "", "", ""],
    ["午", "wǔ", "lunch", "tengah hari"],
    ["”", "", "", ""],
    ["餐", "cān", "meal", "makanan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["小女儿", "xiǎo nǚ ér", "little daughter", "anak perempuan kecil"],
    ["早已", "zǎo yǐ", "already", "sudah"],
    ["吃过", "chī guò", "ate", "telah makan"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["看见", "kàn jiàn", "see", "melihat"],
    ["我", "wǒ", "me", "saya"],
    ["吃", "chī", "eat", "makan"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["快乐", "kuài lè", "happy", "gembira"],
    ["地", "de", "", ""],
    ["凑", "còu", "come close", "mendekat"],
    ["在", "zài", "at", "di"],
    ["我", "wǒ", "me", "saya"],
    ["身边", "shēn biān", "beside", "sisi"],
    ["，", "", "", ""],
    ["要", "yào", "ask", "minta"],
    ["我", "wǒ", "me", "saya"],
    ["夹", "jiā", "pick up", "ambil"],
    ["一块", "yī kuài", "a piece", "sepotong"],
    ["豆腐", "dòu fu", "tofu", "tauhu"],
    ["给", "gěi", "give", "beri"],
    ["她", "tā", "her", "dia"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["给", "gěi", "gave", "memberi"],
    ["了", "le", "", ""],
    ["她", "tā", "her", "dia"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["“", "", "", ""],
    ["啊", "ā", "Ah", "Ah"],
    ["！”", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["高兴", "gāo xìng", "happy", "gembira"],
    ["地", "de", "", ""],
    ["叫", "jiào", "shout", "jerit"],
    ["了", "le", "", ""],
    ["起来", "qǐ lái", "up", "naik"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["你的", "nǐ de", "your", "awak punya"],
    ["筷子", "kuài zi", "chopsticks", "penyepit"],
    ["好", "hǎo", "very", "sangat"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["啊", "a", "", ""],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["我", "wǒ", "I", "saya"],
    ["愣", "lèng", "stunned", "terkejut"],
    ["了", "le", "", ""],
    ["一下", "yī xià", "for a moment", "seketika"],
    ["，", "", "", ""],
    ["才", "cái", "then", "barulah"],
    ["想到", "xiǎng dào", "realize", "sedar"],
    ["，", "", "", ""],
    ["也许", "yě xǔ", "perhaps", "mungkin"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["天冷", "tiān lěng", "weather cold", "cuaca sejuk"],
    ["，", "", "", ""],
    ["菜", "cài", "dishes", "masakan"],
    ["都", "dōu", "all", "semua"],
    ["炖得", "dùn de", "stewed", "direbus"],
    ["滚烫", "gǔn tàng", "boiling hot", "sangat panas"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["筷子", "kuài zi", "chopsticks", "penyepit"],
    ["也就", "yě jiù", "then", "maka"],
    ["暖和", "nuǎn huo", "warm", "hangat"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["她", "tā", "she", "dia"],
    ["对", "duì", "to", "terhadap"],
    ["一双", "yī shuāng", "a pair", "sepasang"],
    ["简单", "jiǎn dān", "simple", "mudah"],
    ["的", "de", "", ""],
    ["筷子", "kuài zi", "chopsticks", "penyepit"],
    ["的", "de", "", ""],
    ["温度", "wēn dù", "temperature", "suhu"],
    ["竟", "jìng", "actually", "sebenarnya"],
    ["表示", "biǎo shì", "express", "menyatakan"],
    ["这样", "zhè yàng", "such", "begitu"],
    ["由衷", "yóu zhōng", "sincere", "ikhlas"],
    ["的", "de", "", ""],
    ["愉快", "yú kuài", "joy", "kegembiraan"],
    ["，", "", "", ""],
    ["这样", "zhè yàng", "such", "begitu"],
    ["惊天动地", "jīng tiān dòng dì", "earth-shattering", "bergempa"],
    ["的", "de", "", ""],
    ["欢呼", "huān hū", "cheer", "sorakan"],
    ["，", "", "", ""],
    ["却是", "què shì", "but it is", "tetapi ia adalah"],
    ["我", "wǒ", "I", "saya"],
    ["不曾", "bù céng", "never", "tidak pernah"],
    ["体会过", "tǐ huì guò", "experienced", "alami"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["世人", "shì rén", "people", "orang ramai"],
    ["只会", "zhǐ huì", "only", "hanya"],
    ["赞美", "zàn měi", "praise", "memuji"],
    ["佳酿", "jiā niàng", "fine wine", "wain berkualiti"],
    ["，", "", "", ""],
    ["赞美", "zàn měi", "praise", "memuji"],
    ["丰盛", "fēng shèng", "lavish", "mewah"],
    ["的", "de", "", ""],
    ["筵席", "yán xí", "feast", "kenduri"],
    ["，", "", "", ""],
    ["赞美", "zàn měi", "praise", "memuji"],
    ["那", "nà", "that", "itu"],
    ["足以", "zú yǐ", "enough to", "cukup untuk"],
    ["称为", "chēng wéi", "call", "dipanggil"],
    ["伟大", "wěi dà", "great", "hebat"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "things", "benda"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["一个", "yī gè", "a", "seorang"],
    ["三岁", "sān suì", "three-year-old", "tiga tahun"],
    ["的", "de", "", ""],
    ["小女孩", "xiǎo nǚ hái", "little girl", "budak perempuan kecil"],
    ["却", "què", "however", "namun"],
    ["懂得", "dǒng de", "know how", "tahu"],
    ["享受", "xiǎng shòu", "enjoy", "menikmati"],
    ["一点点", "yī diǎn diǎn", "a little bit", "sedikit"],
    ["筷子", "kuài zi", "chopsticks", "penyepit"],
    ["尖端", "jiān duān", "tip", "hujung"],
    ["的", "de", "", ""],
    ["温度", "wēn dù", "temperature", "suhu"],
    ["，", "", "", ""],
    ["在", "zài", "in", "pada"],
    ["一个", "yī gè", "a", "sebuah"],
    ["寒冷", "hán lěng", "cold", "sejuk"],
    ["的", "de", "", ""],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段（小标题：我现在知道左右了）

    // ===== 第6段 =====
    ["我", "wǒ", "I", "saya"],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["知道", "zhī dào", "know", "tahu"],
    ["左右", "zuǒ yòu", "left and right", "kiri dan kanan"],
    ["了", "le", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["摔了", "shuāi le", "fell", "jatuh"],
    ["一跤", "yī jiāo", "a fall", "jatuh"],
    ["，", "", "", ""],
    ["当时", "dāng shí", "at that time", "pada masa itu"],
    ["也", "yě", "also", "juga"],
    ["没哭", "méi kū", "didn't cry", "tidak menangis"],
    ["，", "", "", ""],
    ["两天后", "liǎng tiān hòu", "two days later", "dua hari kemudian"],
    ["才发现", "cái fā xiàn", "then discovered", "baru sedar"],
    ["锁骨", "suǒ gǔ", "collarbone", "tulang selangka"],
    ["受了伤", "shòu le shāng", "injured", "cedera"],
    ["。", "", "", ""],
    ["她的", "tā de", "her", "dia punya"],
    ["左手", "zuǒ shǒu", "left hand", "tangan kiri"],
    ["因此", "yīn cǐ", "therefore", "oleh itu"],
    ["举", "jǔ", "raise", "angkat"],
    ["不起来", "bù qǐ lái", "cannot", "tidak dapat"],
    ["，", "", "", ""],
    ["又痛", "yòu tòng", "painful", "sakit"],
    ["又", "yòu", "and", "dan"],
    ["不方便", "bù fāng biàn", "inconvenient", "tidak selesa"],
    ["，", "", "", ""],
    ["要康复", "yào kāng fù", "to recover", "untuk pulih"],
    ["还", "hái", "still", "masih"],
    ["得", "děi", "need", "perlu"],
    ["很长", "hěn cháng", "very long", "sangat panjang"],
    ["一段时间", "yī duàn shí jiān", "a period of time", "satu tempoh masa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["我", "wǒ", "I", "saya"],
    ["心里", "xīn lǐ", "in heart", "dalam hati"],
    ["当然", "dāng rán", "of course", "tentu"],
    ["不舒服", "bù shū fu", "uncomfortable", "tidak selesa"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["她", "tā", "she", "dia"],
    ["自己", "zì jǐ", "herself", "dirinya sendiri"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["了", "le", "", ""],
    ["一个", "yī gè", "a", "sebuah"],
    ["意外", "yì wài", "unexpected", "tidak disangka"],
    ["的", "de", "", ""],
    ["收获", "shōu huò", "gain", "hasil"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["“", "", "", ""],
    ["哈", "hā", "Ha", "Ha"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["知道", "zhī dào", "know", "tahu"],
    ["哪边", "nǎ biān", "which side", "sebelah mana"],
    ["是", "shì", "is", "ialah"],
    ["左边", "zuǒ biān", "left side", "sebelah kiri"],
    ["了", "le", "", ""],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["她", "tā", "she", "dia"],
    ["太小", "tài xiǎo", "too young", "terlalu kecil"],
    ["，", "", "", ""],
    ["一直", "yī zhí", "always", "selalu"],
    ["搞不清楚", "gǎo bù qīng chu", "can't figure out", "tidak dapat membezakan"],
    ["左右", "zuǒ yòu", "left and right", "kiri dan kanan"],
    ["，", "", "", ""],
    ["这下", "zhè xià", "this time", "kali ini"],
    ["好", "hǎo", "good", "baik"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["知道", "zhī dào", "know", "tahu"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["痛", "tòng", "painful", "sakit"],
    ["的", "de", "", ""],
    ["那边", "nà biān", "that side", "sebelah sana"],
    ["就是", "jiù shì", "is", "ialah"],
    ["左", "zuǒ", "left", "kiri"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["有", "yǒu", "There is", "Ada"],
    ["一句", "yī jù", "a", "sebuah"],
    ["话", "huà", "saying", "kata"],
    ["说", "shuō", "says", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["上帝", "shàng dì", "God", "Tuhan"],
    ["关", "guān", "close", "tutup"],
    ["上", "shàng", "up", "atas"],
    ["了", "le", "", ""],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["的", "de", "", ""],
    ["门", "mén", "doors", "pintu"],
    ["，", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["还", "hái", "still", "masih"],
    ["会", "huì", "will", "akan"],
    ["给", "gěi", "give", "beri"],
    ["你", "nǐ", "you", "awak"],
    ["留", "liú", "leave", "tinggalkan"],
    ["一扇", "yī shàn", "a", "sebuah"],
    ["窗", "chuāng", "window", "tingkap"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["我们", "wǒ men", "We", "Kita"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["不甘心", "bù gān xīn", "unwilling", "tidak rela"],
    ["地", "de", "", ""],
    ["哭着", "kū zhe", "crying", "menangis"],
    ["去", "qù", "go", "pergi"],
    ["捶", "chuí", "beat", "pukul"],
    ["那", "nà", "that", "itu"],
    ["厚重", "hòu zhòng", "thick", "tebal"],
    ["的", "de", "", ""],
    ["门", "mén", "door", "pintu"],
    ["，", "", "", ""],
    ["却", "què", "but", "tetapi"],
    ["忘记", "wàng jì", "forget", "lupa"],
    ["那", "nà", "that", "itu"],
    ["个", "gè", "", ""],
    ["开向", "kāi xiàng", "open to", "terbuka ke"],
    ["清风", "qīng fēng", "breeze", "angin sepoi-sepoi"],
    ["明月", "míng yuè", "bright moon", "bulan terang"],
    ["的", "de", "", ""],
    ["窗", "chuāng", "window", "tingkap"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段（小标题：我并不要赢别人）

    // ===== 第13段 =====
    ["我", "wǒ", "I", "Saya"],
    ["并", "bìng", "and", "dan"],
    ["不要", "bù yào", "do not want", "tidak mahu"],
    ["赢", "yíng", "win", "menang"],
    ["别人", "bié rén", "others", "orang lain"],

    ["\n", "", "", ""], // 👈 第14段

    // ===== 第14段 =====
    ["诗诗", "shī shī", "Shishi", "Shishi"],
    ["显然", "xiǎn rán", "obviously", "jelas"],
    ["很喜欢", "hěn xǐ huān", "really like", "sangat suka"],
    ["毛笔", "máo bǐ", "calligraphy brush", "berus kaligrafi"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["几乎", "jī hū", "almost", "hampir"],
    ["觉得", "jué de", "feel", "rasa"],
    ["那", "nà", "that", "itu"],
    ["是", "shì", "is", "ialah"],
    ["一种", "yī zhǒng", "a kind of", "sejenis"],
    ["魔术", "mó shù", "magic", "sihir"],
    ["。", "", "", ""],
    ["虽然", "suī rán", "although", "walaupun"],
    ["他的", "tā de", "his", "dia punya"],
    ["书法", "shū fǎ", "calligraphy", "kaligrafi"],
    ["剑拔弩张", "jiàn bá nǔ zhāng", "tense and aggressive", "tegang"],
    ["，", "", "", ""],
    ["一点", "yī diǎn", "a bit", "sedikit"],
    ["也", "yě", "also", "juga"],
    ["不好看", "bù hǎo kàn", "not pretty", "tidak cantik"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "moreover", "lagipun"],
    ["最糟糕", "zuì zāo gāo", "worst", "paling teruk"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["不是", "bù shì", "either", "sama ada"],
    ["黑墨汁", "hēi mò zhī", "black ink", "dakwat hitam"],
    ["滴脏", "dī zāng", "drip and stain", "titis dan kotor"],
    ["了", "le", "", ""],
    ["左上角", "zuǒ shàng jiǎo", "top left corner", "penjuru kiri atas"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "or", "atau"],
    ["污手印", "wū shǒu yìn", "dirty handprint", "cap tangan kotor"],
    ["弄坏", "nòng huài", "spoil", "merosakkan"],
    ["了", "le", "", ""],
    ["右下角", "yòu xià jiǎo", "bottom right corner", "penjuru kanan bawah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    // ===== 第15段 =====
    ["不过", "bù guò", "however", "bagaimanapun"],
    ["，", "", "", ""],
    ["无论如何", "wú lùn rú hé", "no matter what", "apa pun"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["还是", "hái shì", "still", "masih"],
    ["很喜欢", "hěn xǐ huān", "really like", "sangat suka"],
    ["毛笔", "máo bǐ", "calligraphy brush", "berus kaligrafi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    // ===== 第16段 =====
    ["那天", "nà tiān", "that day", "hari itu"],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["独自一人", "dú zì yī rén", "alone", "bersendirian"],
    ["练字", "liàn zì", "practice calligraphy", "berlatih menulis"],
    ["，", "", "", ""],
    ["被", "bèi", "by", "oleh"],
    ["一位", "yī wèi", "a", "seorang"],
    ["长辈", "zhǎng bèi", "elder", "orang tua"],
    ["看到", "kàn dào", "see", "melihat"],
    ["，", "", "", ""],
    ["那位", "nà wèi", "that", "itu"],
    ["长辈", "zhǎng bèi", "elder", "orang tua"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["嗯", "ēn", "Hmm", "Hmm"],
    ["，", "", "", ""],
    ["真好", "zhēn hǎo", "very good", "sangat baik"],
    ["，", "", "", ""],
    ["你要", "nǐ yào", "you will", "awak akan"],
    ["进步", "jìn bù", "improve", "maju"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "in", "di"],
    ["班上", "bān shàng", "in class", "di kelas"],
    ["就会", "jiù huì", "will", "akan"],
    ["赢", "yíng", "win", "menang"],
    ["别人", "bié rén", "others", "orang lain"],
    ["了", "le", "", ""],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    // ===== 第17段 =====
    ["我", "wǒ", "I", "saya"],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["暗叫", "àn jiào", "thought silently", "berfikir dalam hati"],
    ["不妙", "bù miào", "not good", "tidak baik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    // ===== 第18段 =====
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["才", "cái", "just", "baru"],
    ["不要", "bù yào", "don't want", "tidak mahu"],
    ["赢", "yíng", "win", "menang"],
    ["别人", "bié rén", "others", "orang lain"],
    ["！”", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["不屑", "bù xiè", "contemptuously", "bersikap tidak peduli"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第19段

    // ===== 第19段 =====
    ["“", "", "", ""],
    ["那", "nà", "Then", "Kalau begitu"],
    ["你", "nǐ", "you", "awak"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["要", "yào", "want", "mahu"],
    ["练字", "liàn zì", "practice calligraphy", "berlatih menulis"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    // ===== 第20段 =====
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["写好了", "xiě hǎo le", "write well", "tulis dengan baik"],
    ["，", "", "", ""],
    ["自己", "zì jǐ", "myself", "diri sendiri"],
    ["看了", "kàn le", "look", "melihat"],
    ["高兴", "gāo xìng", "happy", "gembira"],
    ["就是", "jiù shì", "that's it", "itulah"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["才不要", "cái bù yào", "really don't want", "tidak mahu"],
    ["赢", "yíng", "win", "menang"],
    ["别人", "bié rén", "others", "orang lain"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第21段

    // ===== 第21段 =====
    ["我", "wǒ", "I", "saya"],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["暗暗", "àn àn", "secretly", "diam-diam"],
    ["喝彩", "hè cǎi", "cheer", "memuji"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第22段

    // ===== 第22段 =====
    ["那天", "nà tiān", "that day", "hari itu"],
    ["晚上", "wǎn shàng", "evening", "malam"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["和他", "hé tā", "with him", "dengan dia"],
    ["又", "yòu", "again", "lagi"],
    ["谈起", "tán qǐ", "talk about", "bercakap tentang"],
    ["这件", "zhè jiàn", "this", "ini"],
    ["事", "shì", "matter", "perkara"],
    ["，", "", "", ""],
    ["表示", "biǎo shì", "express", "menyatakan"],
    ["对", "duì", "to", "terhadap"],
    ["他", "tā", "him", "dia"],
    ["的", "de", "", ""],
    ["激赏", "jī shǎng", "admiration", "kekaguman"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第23段

    // ===== 第23段 =====
    ["“", "", "", ""],
    ["本来嘛", "běn lái ma", "of course", "sememangnya"],
    ["！”", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["理直气壮", "lǐ zhí qì zhuàng", "confidently", "dengan yakin"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["要", "yào", "need", "perlu"],
    ["赢", "yíng", "win", "menang"],
    ["别人", "bié rén", "others", "orang lain"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["只", "zhǐ", "only", "hanya"],
    ["想", "xiǎng", "want", "mahu"],
    ["写好看一点", "xiě hǎo kàn yī diǎn", "write a bit better", "tulis lebih cantik"],
    ["，", "", "", ""],
    ["自己", "zì jǐ", "myself", "diri sendiri"],
    ["高兴", "gāo xìng", "happy", "gembira"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第24段

    // ===== 第24段 =====
    ["不管", "bù guǎn", "no matter", "tidak kira"],
    ["他", "tā", "he", "dia"],
    ["能", "néng", "can", "boleh"],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["写好", "xiě hǎo", "write well", "tulis dengan baik"],
    ["横撇点捺", "héng piě diǎn nà", "basic strokes", "strok asas"],
    ["，", "", "", ""],
    ["不管", "bù guǎn", "no matter", "tidak kira"],
    ["他", "tā", "he", "dia"],
    ["能", "néng", "can", "boleh"],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["临好", "lín hǎo", "copy well", "tiru dengan baik"],
    ["柳公权", "liǔ gōng quán", "Liu Gongquan", "Liu Gongquan"],
    ["、", "", "", ""],
    ["颜真卿", "yán zhēn qīng", "Yan Zhenqing", "Yan Zhenqing"],
    ["的", "de", "", ""],
    ["作品", "zuò pǐn", "works", "karya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["最", "zuì", "most", "paling"],
    ["喜欢", "xǐ huān", "like", "suka"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["并", "bìng", "and", "dan"],
    ["不想", "bù xiǎng", "doesn't want", "tidak mahu"],
    ["压倒", "yā dǎo", "overwhelm", "mengalahkan"],
    ["什么", "shén me", "any", "mana-mana"],
    ["人", "rén", "person", "orang"],
    ["的", "de", "", ""],
    ["那份", "nà fèn", "that", "itu"],
    ["坦荡", "tǎn dàng", "openness", "ikhlas"],
    ["。", "", "", ""],
    ["竞争心", "jìng zhēng xīn", "competitive spirit", "semangat persaingan"],
    ["也许", "yě xǔ", "perhaps", "mungkin"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["促使", "cù shǐ", "drive", "mendorong"],
    ["一个人", "yī gè rén", "a person", "seseorang"],
    ["成为", "chéng wéi", "become", "menjadi"],
    ["成功", "chéng gōng", "successful", "berjaya"],
    ["的", "de", "", ""],
    ["企业家", "qǐ yè jiā", "entrepreneur", "usahawan"],
    ["或", "huò", "or", "atau"],
    ["艺术家", "yì shù jiā", "artist", "seniman"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["无心相竞", "wú xīn xiāng jìng", "not competing", "tidak bersaing"],
    ["的", "de", "", ""],
    ["天真", "tiān zhēn", "innocence", "kepolosan"],
    ["，", "", "", ""],
    ["使", "shǐ", "makes", "membuat"],
    ["人", "rén", "one", "seseorang"],
    ["顿觉", "dùn jué", "suddenly feel", "tiba-tiba rasa"],
    ["海阔天空", "hǎi kuò tiān kōng", "vast and free", "luas dan bebas"],
    ["而", "ér", "and", "dan"],
    ["怡然自得", "yí rán zì dé", "contented", "berpuas hati"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第25段（小标题：它一定很想我）

    // ===== 第25段 =====
    ["它", "tā", "It", "Ia"],
    ["一定", "yī dìng", "surely", "pasti"],
    ["很想", "hěn xiǎng", "miss very much", "rindu sangat"],
    ["我", "wǒ", "me", "saya"],

    ["\n", "", "", ""], // 👈 第26段

    // ===== 第26段 =====
    ["住在", "zhù zài", "live in", "tinggal di"],
    ["公寓", "gōng yù", "apartment", "pangsapuri"],
    ["四楼", "sì lóu", "fourth floor", "tingkat empat"],
    ["，", "", "", ""],
    ["养狗", "yǎng gǒu", "keep a dog", "pelihara anjing"],
    ["当然", "dāng rán", "of course", "tentu"],
    ["成了", "chéng le", "became", "menjadi"],
    ["一种", "yī zhǒng", "a kind of", "sejenis"],
    ["奢望", "shē wàng", "luxury", "kemewahan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第27段

    // ===== 第27段 =====
    ["但", "dàn", "But", "Tetapi"],
    ["距离", "jù lí", "distance", "jarak"],
    ["我们家", "wǒ men jiā", "our home", "rumah kami"],
    ["一百米", "yī bǎi mǐ", "one hundred meters", "seratus meter"],
    ["，", "", "", ""],
    ["却", "què", "however", "namun"],
    ["有", "yǒu", "there are", "ada"],
    ["三家", "sān jiā", "three", "tiga"],
    ["狗店", "gǒu diàn", "dog shops", "kedai anjing"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["带", "dài", "take", "bawa"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["晴晴", "qíng qíng", "Qingqing", "Qingqing"],
    ["出门", "chū mén", "go out", "keluar"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["总是", "zǒng shì", "always", "selalu"],
    ["绕道", "rào dào", "detour", "jalan memutar"],
    ["去看", "qù kàn", "go see", "pergi melihat"],
    ["一下", "yī xià", "a bit", "sedikit"],
    ["狗", "gǒu", "dogs", "anjing"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第28段

    // ===== 第28段 =====
    ["晴晴", "qíng qíng", "Qingqing", "Qingqing"],
    ["爱上", "ài shàng", "fell in love with", "jatuh cinta pada"],
    ["了", "le", "", ""],
    ["一只", "yī zhī", "a", "seekor"],
    ["肥肥滚滚", "féi féi gǔn gǔn", "plump", "gemuk bulat"],
    ["，", "", "", ""],
    ["身长", "shēn cháng", "body length", "panjang badan"],
    ["不足", "bù zú", "less than", "kurang daripada"],
    ["一尺", "yī chǐ", "one foot", "satu kaki"],
    ["的", "de", "", ""],
    ["棕色", "zōng sè", "brown", "coklat"],
    ["小狗", "xiǎo gǒu", "puppy", "anak anjing"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第29段

    // ===== 第29段 =====
    ["有时候", "yǒu shí hou", "sometimes", "kadang-kadang"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["带着", "dài zhe", "bring", "membawa"],
    ["干酪", "gān lào", "cheese", "keju"],
    ["，", "", "", ""],
    ["征得", "zhēng de", "get permission", "dapat kebenaran"],
    ["老板", "lǎo bǎn", "shop owner", "pemilik kedai"],
    ["的", "de", "", ""],
    ["同意", "tóng yì", "consent", "persetujuan"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["笼子", "lóng zi", "cage", "sangkar"],
    ["的", "de", "", ""],
    ["铁条", "tiě tiáo", "iron bars", "besi palang"],
    ["间", "jiān", "between", "di antara"],
    ["喂", "wèi", "feed", "beri makan"],
    ["那只", "nà zhī", "that", "itu"],
    ["小狗", "xiǎo gǒu", "puppy", "anak anjing"],
    ["。", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["多半", "duō bàn", "mostly", "kebanyakan"],
    ["只顾", "zhǐ gù", "only care", "hanya peduli"],
    ["玩", "wán", "play", "bermain"],
    ["，", "", "", ""],
    ["不肯", "bù kěn", "refuse", "enggan"],
    ["好好", "hǎo hǎo", "properly", "dengan baik"],
    ["地", "de", "", ""],
    ["吃", "chī", "eat", "makan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第30段

    // ===== 第30段 =====
    ["“", "", "", ""],
    ["那只", "nà zhī", "That", "Itu"],
    ["小狗", "xiǎo gǒu", "puppy", "anak anjing"],
    ["好", "hǎo", "so", "sangat"],
    ["可怜", "kě lián", "pitiful", "kasihan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第31段

    // ===== 第31段 =====
    ["“", "", "", ""],
    ["为什么", "wèi shén me", "Why", "Kenapa"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第32段

    // ===== 第32段 =====
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["来看", "lái kàn", "come see", "datang melihat"],
    ["它", "tā", "it", "ia"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["一定", "yī dìng", "surely", "pasti"],
    ["很想", "hěn xiǎng", "miss very much", "rindu sangat"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第33段

    // ===== 第33段 =====
    ["我", "wǒ", "I", "saya"],
    ["惊讶", "jīng yà", "surprised", "terkejut"],
    ["她", "tā", "she", "dia"],
    ["从", "cóng", "from", "dari"],
    ["哪里", "nǎ lǐ", "where", "mana"],
    ["学来", "xué lái", "learned", "belajar"],
    ["这份", "zhè fèn", "this", "ini"],
    ["温柔敦厚", "wēn róu dūn hòu", "gentle and kind", "lembut dan baik"],
    ["，", "", "", ""],
    ["不说", "bù shuō", "not say", "tidak berkata"],
    ["自己", "zì jǐ", "herself", "dirinya sendiri"],
    ["想狗", "xiǎng gǒu", "miss the dog", "rindu anjing"],
    ["，", "", "", ""],
    ["却", "què", "but", "tetapi"],
    ["担心", "dān xīn", "worry", "bimbang"],
    ["狗想自己", "gǒu xiǎng zì jǐ", "dog misses her", "anjing rindu dia"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第34段

    // ===== 第34段 =====
    ["“", "", "", ""],
    ["是的", "shì de", "Yes", "Ya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["很", "hěn", "very", "sangat"],
    ["庄严", "zhuāng yán", "solemnly", "dengan khusyuk"],
    ["地", "de", "", ""],
    ["看着", "kàn zhe", "look at", "melihat"],
    ["她", "tā", "her", "dia"],
    ["，", "", "", ""],
    ["经历", "jīng lì", "experience", "melalui"],
    ["某些", "mǒu xiē", "some", "sesetengah"],
    ["伤心", "shāng xīn", "sadness", "kesedihan"],
    ["，", "", "", ""],
    ["对", "duì", "for", "bagi"],
    ["小孩子", "xiǎo hái zi", "children", "kanak-kanak"],
    ["来说", "lái shuō", "as for", "bagi"],
    ["，", "", "", ""],
    ["几乎", "jī hū", "almost", "hampir"],
    ["是", "shì", "is", "ialah"],
    ["必要", "bì yào", "necessary", "perlu"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["，", "", "", ""],
    ["说不定", "shuō bù dìng", "maybe", "mungkin"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["长大了", "zhǎng dà le", "grows up", "besar"],
    ["，", "", "", ""],
    ["它的", "tā de", "its", "ia punya"],
    ["主人", "zhǔ rén", "owner", "tuan"],
    ["带", "dài", "take", "bawa"],
    ["它", "tā", "it", "ia"],
    ["出来", "chū lái", "out", "keluar"],
    ["散步", "sàn bù", "walk", "berjalan"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["还会", "hái huì", "still will", "masih akan"],
    ["认得", "rèn de", "recognize", "kenal"],
    ["你", "nǐ", "you", "awak"],
    ["，", "", "", ""],
    ["记得", "jì de", "remember", "ingat"],
    ["你", "nǐ", "you", "awak"],
    ["给它", "gěi tā", "gave it", "memberi ia"],
    ["吃过", "chī guò", "ate", "makan"],
    ["干酪", "gān lào", "cheese", "keju"],
    ["，", "", "", ""],
    ["它会", "tā huì", "it will", "ia akan"],
    ["跑过来", "pǎo guò lái", "run over", "lari ke sini"],
    ["闻闻", "wén wén", "smell", "cium"],
    ["你", "nǐ", "you", "awak"],
    ["……”", "", "", ""],

    ["\n", "", "", ""], // 👈 第35段

    // ===== 第35段 =====
    ["“", "", "", ""],
    ["当然啦", "dāng rán la", "Of course", "Tentu"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["当然", "dāng rán", "of course", "tentu"],
    ["会", "huì", "will", "akan"],
    ["记得", "jì de", "remember", "ingat"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["味道", "wèi dào", "smell", "bau"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第36段

    // ===== 第36段 =====
    ["红砖", "hóng zhuān", "red brick", "bata merah"],
    ["的", "de", "", ""],
    ["人行道", "rén xíng dào", "sidewalk", "kaki lima"],
    ["上", "shàng", "on", "atas"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["牵着手", "qiān zhe shǒu", "holding hands", "berganding tangan"],
    ["慢慢", "màn màn", "slowly", "perlahan"],
    ["地", "de", "", ""],
    ["走", "zǒu", "walk", "berjalan"],
    ["。", "", "", ""],
    ["天地", "tiān dì", "The world", "Dunia"],
    ["是", "shì", "is", "ialah"],
    ["如此", "rú cǐ", "so", "begitu"],
    ["大", "dà", "big", "besar"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["不知道", "bù zhī dào", "don't know", "tidak tahu"],
    ["自己", "zì jǐ", "ourselves", "diri kita"],
    ["是", "shì", "are", "adalah"],
    ["在", "zài", "in", "dalam"],
    ["失去", "shī qù", "losing", "kehilangan"],
    ["，", "", "", ""],
    ["还是", "hái shì", "or", "atau"],
    ["在", "zài", "in", "dalam"],
    ["拥有", "yōng yǒu", "having", "mempunyai"],
    ["……", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
